using System.Text.Json;
using Qeli.Shared.Crypto;

namespace Qeli.Shared.Protocol;

/// <summary>
/// Checks this implementation's WIRE codec against the SHARED cross-language fixtures
/// <c>conformance/packet-decode.json</c> and <c>conformance/replay-window.json</c> — the
/// same files the Rust, Kotlin and Swift suites read. Both are GENERATED by the Rust canon
/// (<c>qeli/src/gen_conformance_main.rs</c>).
///
/// WHY: the record format and the anti-replay window are reimplemented from scratch in four
/// languages. Decoding is deterministic given (key, record), so it pins with no test seam;
/// the window is pure state, so it pins as a table of verdicts. Before these files, nothing
/// compared the four — which is how M6 (the data-plane nonce) shipped in three of them.
/// </summary>
public static class WireConformance
{
    /// <summary>
    /// Run both fixtures, reporting each assertion through <paramref name="check"/>.
    ///
    /// A missing fixture file is a SKIP (a shipped app has no repository next to it) —
    /// except under <c>QELI_CONFORMANCE_REQUIRED=1</c>, which CI sets so a file that moved
    /// cannot turn the gate into a silent no-op.
    /// </summary>
    public static bool Run(Action<string, bool> check)
    {
        bool ok = RunDecode(check);
        ok &= RunReplay(check);
        ok &= RunHkdf(check);
        ok &= RunQuic(check);
        ok &= RunUdpFrag(check);
        ok &= RunCtrlFrame(check);
        ok &= RunMtuLadder(check);
        ok &= RunIniBounds(check);
        return ok;
    }

    /// <summary>Range checks on the hand-writable flat INI. Not fixture-driven — these are
    /// policy, and the failure they guard is silent: an out-of-range value that parses.</summary>
    private static bool RunIniBounds(Action<string, bool> check)
    {
        static Model.VpnConfig Ini(params string[] extra) =>
            Model.VpnConfig.FromIni("[qeli]\nserver = 1.2.3.4:443\nuser = u\npass = p\n"
                                    + string.Join("\n", extra) + "\n");

        // A timeout above ~2.1M seconds used to survive parsing, then overflow the int
        // multiply in VpnTunnelBase (`(int)secs * 1000`) into a NEGATIVE timeout — an
        // instantly-expired connect rather than a long one.
        var huge = Ini("timeout = 999999999");
        bool timeoutClamped = huge.ConnectionTimeoutSecs is >= 1 and <= 300;
        bool noOverflow = (int)huge.ConnectionTimeoutSecs * 1000 > 0;
        check("ini-bounds: an absurd timeout is clamped into range", timeoutClamped);
        check("ini-bounds: the clamped timeout cannot overflow to a negative ms value", noOverflow);
        bool zeroTimeout = Ini("timeout = 0").ConnectionTimeoutSecs == 30;
        bool negTimeout = Ini("timeout = -5").ConnectionTimeoutSecs == 30;
        check("ini-bounds: a zero/negative timeout falls back to the default", zeroTimeout && negTimeout);
        bool sane = Ini("timeout = 45").ConnectionTimeoutSecs == 45;
        check("ini-bounds: a valid timeout is left alone", sane);

        // padding_min > padding_max is an inverted range; a five-digit padding is past the
        // ceiling. Each field only checked `>= 0` on its own, so both parsed.
        var inverted = Ini("padding_min = 900", "padding_max = 300");
        bool ordered = inverted.PaddingMin <= inverted.PaddingMax;
        var over = Ini("padding_min = 0", "padding_max = 60000");
        bool capped = over.PaddingMax <= 1400;
        check("ini-bounds: an inverted padding range is corrected", ordered);
        check("ini-bounds: padding is capped at the ceiling", capped);
        var keep = Ini("padding_min = 10", "padding_max = 200");
        bool kept = keep.PaddingMin == 10 && keep.PaddingMax == 200;
        check("ini-bounds: a valid padding range is left alone", kept);

        return timeoutClamped && noOverflow && zeroTimeout && negTimeout && sane
               && ordered && capped && kept;
    }

    /// <summary>The path-MTU ladder's floor. Not fixture-driven — it is a policy, not a wire
    /// format. What this catches is the rung/path unit confusion (#12): rungs are INNER tunnel
    /// MTUs, 1280 is an OUTER path limit, so a floor of 1280 asks a 1280-byte path for
    /// 1280 + overhead and every rung fails on exactly the narrow paths probing exists for.</summary>
    private static bool RunMtuLadder(Action<string, bool> check)
    {
        // Both extremes this codebase actually produces: bare IPv4 UDP, and the worst case of
        // obfs seal (13) + QUIC short header (9) + UDP (8) + IPv6 (40), each over a 48-byte record.
        bool floorFits = true, descending = true, nonEmpty = true;
        foreach (int overhead in new[] { 48 + 8 + 20, 48 + 13 + 9 + 8 + 40 })
        {
            var ladder = Vpn.VpnTunnelBase.MtuProbeLadder(1400, overhead);
            nonEmpty &= ladder.Length > 0;
            if (ladder.Length == 0) continue;
            // The narrowest rung's WIRE size must fit a 1280-byte path.
            floorFits &= ladder[^1] + overhead <= 1280;
            for (int i = 1; i < ladder.Length; i++) descending &= ladder[i] < ladder[i - 1];
        }
        check("mtu-ladder: ladder is never empty", nonEmpty);
        check("mtu-ladder: lowest rung fits a 1280-byte path once framing is counted", floorFits);
        check("mtu-ladder: rungs are strictly descending and deduped", descending);

        // A ceiling already below the floor must still yield something to try, not an empty
        // ladder (which would report "no result" and silently keep the pushed MTU).
        var tiny = Vpn.VpnTunnelBase.MtuProbeLadder(700, 48 + 13 + 9 + 8 + 40);
        check("mtu-ladder: a low ceiling still produces a rung", tiny.Length > 0 && tiny[0] <= 700);

        return floorFits && descending && nonEmpty && tiny.Length > 0;
    }

    /// <summary>In-tunnel control frames. Not fixture-driven — the frame is six bytes, so the
    /// bytes themselves are pinned here and in the Rust/Kotlin/Swift tests. What this catches is
    /// a port drifting on byte order or on the magic, which would make the server read a
    /// nonsense MTU (or route the frame as a packet).</summary>
    private static bool RunCtrlFrame(Action<string, bool> check)
    {
        // 1280 = 0x0500, big-endian. Same vector in every implementation.
        var expected = new byte[] { 0xC1, 0x9B, 0x01, 0x02, 0x05, 0x00 };
        bool ok = Hex(CtrlFrame.MtuReport(1280)) == Hex(expected);
        check("ctrl: MtuReport(1280) matches the shared vector", ok);

        // The discriminator that keeps control frames and IP packets apart, in both directions.
        bool disjoint = CtrlFrame.IsCtrl(expected)
            && !CtrlFrame.IsCtrl(new byte[] { 0x45, 0x00, 0x00, 0x28 })   // IPv4
            && !CtrlFrame.IsCtrl(new byte[] { 0x60, 0x00, 0x00, 0x00 })   // IPv6
            && !CtrlFrame.IsCtrl(System.Array.Empty<byte>());             // heartbeat
        check("ctrl: frames and IP packets cannot be confused", disjoint);

        // Out-of-range values are clamped, never wrapped into a plausible small MTU.
        bool clamped = Hex(CtrlFrame.MtuReport(70_000)) == "c19b0102ffff"
            && Hex(CtrlFrame.MtuReport(-1)) == "c19b01020000";
        check("ctrl: out-of-range MTU is clamped, not wrapped", clamped);

        return ok && disjoint && clamped;
    }

    /// <summary>App-layer fragmentation of the big UDP handshake messages. The reassembler is
    /// fed by the NETWORK — out of order, with duplicates, with gaps, and with whatever an
    /// attacker sends — so the malformed cases matter as much as the happy ones. The failure
    /// this pins against is a handshake that hangs only on LTE.</summary>
    private static bool RunUdpFrag(Action<string, bool> check)
    {
        var root = Load("udp-frag.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "udp-frag", check)) return false;

            check("udp-frag: fixture MaxChunk matches this build",
                r.GetProperty("max_chunk").GetInt32() == UdpFrag.MaxChunk);
            // The receive bound is pinned separately and is LARGER: bounding receive by the
            // send budget would reject every handshake from a pre-#14 peer.
            check("udp-frag: fixture MaxChunkAccept matches this build",
                r.GetProperty("max_chunk_accept").GetInt32() == UdpFrag.MaxChunkAccept);
            check("udp-frag: fixture MaxFrags matches this build",
                r.GetProperty("max_frags").GetInt32() == UdpFrag.MaxFrags);
            check("udp-frag: a legacy 1200-byte chunk still reassembles", LegacyChunkAccepted());

            int n = 0;
            foreach (var c in r.GetProperty("fragment").EnumerateArray())
            {
                n++;
                string name = c.GetProperty("name").GetString() ?? "?";
                byte msgId = (byte)c.GetProperty("msg_id").GetInt32();
                var expect = c.GetProperty("expect");

                if (expect.TryGetProperty("reject", out var rej) && rej.GetBoolean())
                {
                    // The oversize body is megabytes, so the fixture records its SHAPE.
                    int len = c.GetProperty("message_len").GetInt32();
                    var big = new byte[len];
                    for (int i = 0; i < len; i++) big[i] = (byte)((i * 31 + 7) % 256);
                    bool refused;
                    try { UdpFrag.Fragment(msgId, big); refused = false; }
                    catch { refused = true; }
                    check($"udp-frag[{name}]: oversize message refused at the sender", refused);
                }
                else
                {
                    var msg = Convert.FromHexString(c.GetProperty("message").GetString()!);
                    var got = UdpFrag.Fragment(msgId, msg).Select(Hex).ToList();
                    var want = expect.GetProperty("fragments").EnumerateArray()
                        .Select(f => f.GetString()!).ToList();
                    check($"udp-frag[{name}]: fragments", got.SequenceEqual(want));
                }
            }

            foreach (var c in r.GetProperty("reassemble").EnumerateArray())
            {
                n++;
                string name = c.GetProperty("name").GetString() ?? "?";
                var expect = c.GetProperty("expect");

                // A FRESH reassembler per case.
                var re = new UdpFrag.Reassembler();
                byte[]? completed = null;
                bool rejected = false;
                foreach (var d in c.GetProperty("feed").EnumerateArray())
                {
                    try
                    {
                        var got = re.Push(Convert.FromHexString(d.GetString()!));
                        if (got != null) { completed = got; break; }
                    }
                    catch { rejected = true; break; }
                }

                if (expect.TryGetProperty("reject", out var rej) && rej.GetBoolean())
                    check($"udp-frag[{name}]: malformed fragment rejected", rejected);
                else if (expect.TryGetProperty("incomplete", out var inc) && inc.GetBoolean())
                    check($"udp-frag[{name}]: stays incomplete", !rejected && completed == null);
                else
                    check($"udp-frag[{name}]: reassembled message",
                        completed != null && Hex(completed) == expect.GetProperty("message").GetString());
            }

            foreach (var c in r.GetProperty("classify").EnumerateArray())
            {
                n++;
                string name = c.GetProperty("name").GetString() ?? "?";
                var d = Convert.FromHexString(c.GetProperty("datagram").GetString()!);
                var e = c.GetProperty("expect");
                bool ok = UdpFrag.IsFragment(d) == e.GetProperty("is_fragment").GetBoolean()
                       && UdpFrag.IsJunk(d) == e.GetProperty("is_junk").GetBoolean()
                       && UdpFrag.IsMtuProbe(d) == e.GetProperty("is_mtu_probe").GetBoolean()
                       && UdpFrag.IsMtuProbeAck(d) == e.GetProperty("is_mtu_probe_ack").GetBoolean();
                check($"udp-frag[{name}]: classification", ok);
            }

            check($"udp-frag: {n} case(s) ran", n > 0);
            return n > 0;
        }
    }

    /// <summary>The four directional key-derivation schemes. Both ends must derive
    /// byte-identical keys or the tunnel does not come up; a subtler divergence — the two
    /// DIRECTIONS swapped — yields a tunnel that authenticates and then decrypts nothing.</summary>
    private static bool RunHkdf(Action<string, bool> check)
    {
        var root = Load("hkdf.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "hkdf", check)) return false;

            int cases = 0;
            foreach (var c in r.GetProperty("cases").EnumerateArray())
            {
                cases++;
                string name = c.GetProperty("name").GetString() ?? "?";
                var inp = c.GetProperty("inputs");
                byte[] In(string k) => Convert.FromHexString(inp.GetProperty(k).GetString()!);

                (byte[] s2c, byte[] c2s) keys = c.GetProperty("scheme").GetString() switch
                {
                    "classic" => Crypto.KeyDerivation.DeriveKeys(In("shared_secret")),
                    "hybrid" => Crypto.KeyDerivation.DeriveKeysHybrid(In("x25519_shared"), In("mlkem_shared")),
                    "bound" => Crypto.KeyDerivation.DeriveKeysBound(In("ee"), In("es")),
                    "hybrid-bound" => Crypto.KeyDerivation.DeriveKeysHybridBound(
                        In("x25519_shared"), In("mlkem_shared"), In("es")),
                    var other => throw new InvalidOperationException($"unknown scheme `{other}`"),
                };

                var expect = c.GetProperty("expect");
                check($"hkdf[{name}]: server_to_client",
                    Hex(keys.s2c) == expect.GetProperty("server_to_client").GetString());
                check($"hkdf[{name}]: client_to_server",
                    Hex(keys.c2s) == expect.GetProperty("client_to_server").GetString());
            }
            check($"hkdf: {cases} case(s) ran", cases > 0);
            return cases > 0;
        }
    }

    /// <summary>QUIC envelope + the crafted packets a parser must survive. The parse half is
    /// attacker-facing: anyone who can send the client a datagram controls those bytes, and a
    /// crafted varint once crashed this very implementation into a reconnect loop.</summary>
    private static bool RunQuic(Action<string, bool> check)
    {
        var root = Load("quic.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "quic", check)) return false;

            int n = 0;
            foreach (var w in r.GetProperty("wrap").EnumerateArray())
            {
                n++;
                string name = w.GetProperty("name").GetString() ?? "?";
                var payload = Convert.FromHexString(w.GetProperty("payload").GetString()!);
                var cid = Convert.FromHexString(w.GetProperty("connection_id").GetString()!);
                // The fixture carries the packet number as an unsigned 32-bit value (Rust and
                // Swift type it that way); this API takes a signed int, so pass the same BIT
                // PATTERN. The wire contract is the four bytes, not the language's idea of sign.
                int pn = unchecked((int)w.GetProperty("packet_number").GetUInt32());

                var packet = Quic.WrapShort(payload, cid, pn);
                check($"quic[{name}]: wrapped packet",
                    Hex(packet) == w.GetProperty("expect").GetProperty("packet").GetString());

                var back = Quic.UnwrapPayload(packet);
                check($"quic[{name}]: payload round-trip",
                    back != null && Hex(back) == Hex(payload));
            }

            foreach (var p in r.GetProperty("parse").EnumerateArray())
            {
                n++;
                string name = p.GetProperty("name").GetString() ?? "?";
                var packet = Convert.FromHexString(p.GetProperty("packet").GetString()!);
                var expect = p.GetProperty("expect");

                // A crafted packet must be rejected CLEANLY — no throw, no hang, no allocation
                // sized from an attacker-supplied length. A throw is a failure here, not a pass.
                byte[]? got;
                try { got = Quic.UnwrapPayload(packet); }
                catch (Exception e)
                {
                    check($"quic[{name}]: crafted packet handled without throwing ({e.GetType().Name})", false);
                    continue;
                }

                if (expect.TryGetProperty("reject", out var rej) && rej.GetBoolean())
                    check($"quic[{name}]: crafted packet rejected", got == null);
                else
                    check($"quic[{name}]: payload",
                        got != null && Hex(got) == expect.GetProperty("payload").GetString());
            }
            check($"quic: {n} case(s) ran", n > 0);
            return n > 0;
        }
    }

    private static bool RunDecode(Action<string, bool> check)
    {
        var root = Load("packet-decode.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "packet-decode", check)) return false;

            int cases = 0;
            foreach (var c in r.GetProperty("cases").EnumerateArray())
            {
                cases++;
                string name = c.GetProperty("name").GetString() ?? "?";
                var key = Convert.FromHexString(c.GetProperty("key").GetString()!);
                var record = Convert.FromHexString(c.GetProperty("record").GetString()!);
                bool raw = c.GetProperty("framing").GetString() == "raw";
                var expect = c.GetProperty("expect");

                // A fresh codec per case: every record carries counter 0, so the cases are
                // independent and a replay rejection can never mask a decode failure.
                var codec = new PacketCodec(new PacketCipher(key), raw: raw);

                if (expect.TryGetProperty("reject", out var rej) && rej.GetBoolean())
                {
                    bool rejected;
                    try { codec.Decrypt(record); rejected = false; }
                    catch { rejected = true; }
                    check($"packet-decode[{name}]: corrupt record rejected", rejected);
                }
                else
                {
                    string want = expect.GetProperty("plaintext").GetString()!;
                    string got;
                    try { got = Convert.ToHexString(codec.Decrypt(record)).ToLowerInvariant(); }
                    catch (Exception e) { got = $"<threw: {e.Message}>"; }
                    check($"packet-decode[{name}]: plaintext", got == want);
                }
            }
            check($"packet-decode: {cases} case(s) ran", cases > 0);
            return cases > 0;
        }
    }

    private static bool RunReplay(Action<string, bool> check)
    {
        var root = Load("replay-window.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "replay-window", check)) return false;

            // The fixture was generated for a specific window size; a build with a different
            // one would fail cases for a reason that has nothing to do with correctness.
            if (r.TryGetProperty("window_size", out var ws))
                check("replay-window: fixture window size matches this build",
                    ws.GetInt32() == PacketCodec.ReplayWindow);

            int cases = 0;
            foreach (var c in r.GetProperty("cases").EnumerateArray())
            {
                cases++;
                string name = c.GetProperty("name").GetString() ?? "?";

                // A FRESH window per case. The codec owns the window, so a fresh codec is a
                // fresh window; the key is irrelevant here (no crypto is exercised).
                var codec = new PacketCodec(new PacketCipher(new byte[32]));

                var seqs = c.GetProperty("seqs").EnumerateArray().Select(v => v.GetInt64()).ToList();
                var want = c.GetProperty("verdicts").EnumerateArray().Select(v => v.GetBoolean()).ToList();
                var got = seqs.Select(codec.AcceptCounter).ToList();

                check($"replay-window[{name}]: verdicts", got.SequenceEqual(want));
            }
            check($"replay-window: {cases} case(s) ran", cases > 0);
            return cases > 0;
        }
    }

    private static string Hex(byte[] b) => Convert.ToHexString(b).ToLowerInvariant();

    /// <summary>A pre-#14 peer slices at 1200, which is ABOVE this build's send budget. The
    /// reassembler must bound by MaxChunkAccept, not MaxChunk, or every legacy handshake is
    /// rejected as "fragment chunk too large".</summary>
    private static bool LegacyChunkAccepted()
    {
        // Not `const`: with both sides constant the compiler folds the guard below and warns
        // the failure branch is unreachable (CS0162) — true today, but the guard is the point.
        int legacy = 1200;
        if (legacy <= UdpFrag.MaxChunk) return false;   // the bounds must actually differ
        var re = new UdpFrag.Reassembler();
        try
        {
            for (byte idx = 0; idx < 2; idx++)
            {
                var d = new byte[UdpFrag.HdrLen + legacy];
                System.Array.Copy(UdpFrag.Magic, d, 3);
                d[3] = UdpFrag.MsgServerHello; d[4] = idx; d[5] = 2;
                for (int i = UdpFrag.HdrLen; i < d.Length; i++) d[i] = (byte)'L';
                var done = re.Push(d);
                if (idx == 0 && done != null) return false;
                if (idx == 1) return done != null && done.Length == legacy * 2;
            }
        }
        catch (System.Exception) { return false; }
        return false;
    }

    /// <summary>A platform on the fixture's `platforms` list MUST actually run it — otherwise
    /// a renamed primitive leaves this green having verified nothing.</summary>
    private static bool RequireListed(JsonElement root, string label, Action<string, bool> check)
    {
        bool listed = false;
        if (root.TryGetProperty("platforms", out var platforms))
            foreach (var p in platforms.EnumerateArray())
                if (p.GetString() == "csharp") listed = true;
        check($"{label}: csharp listed in `platforms`", listed);
        return listed;
    }

    /// <summary>Load a fixture, or report a SKIP/failure and return null.</summary>
    private static JsonElement? Load(string file, Action<string, bool> check, out JsonDocument? doc)
    {
        doc = null;
        var path = Find(file);
        if (path == null)
        {
            bool required = Environment.GetEnvironmentVariable("QELI_CONFORMANCE_REQUIRED") == "1";
            check($"wire conformance fixtures found (conformance/{file})", !required);
            if (!required)
                Console.WriteLine($"  [SKIP] {file} — fixtures not found (not running from a source tree)");
            return required ? null : (JsonElement?)default(JsonElement);
        }
        try
        {
            doc = JsonDocument.Parse(File.ReadAllText(path));
            return doc.RootElement;
        }
        catch (Exception e)
        {
            check($"{file} parse ({e.Message})", false);
            return null;
        }
    }

    /// <summary>Walk up from the working directory — the selftest runs from different
    /// directories on Windows and macOS, and a fixed path would silently find nothing.</summary>
    private static string? Find(string file)
    {
        var env = Environment.GetEnvironmentVariable("QELI_CONFORMANCE_FIXTURES_DIR");
        if (!string.IsNullOrEmpty(env))
        {
            var p = Path.Combine(env, file);
            if (File.Exists(p)) return p;
        }
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir != null)
        {
            var candidate = Path.Combine(dir.FullName, "conformance", file);
            if (File.Exists(candidate)) return candidate;
            dir = dir.Parent;
        }
        return null;
    }
}
