using System.Text.Json;
using Qeli.Shared.Crypto;

namespace Qeli.Shared.Protocol;

/// <summary>
/// Checks this implementation's WIRE codec against the SHARED cross-language fixtures
/// <c>conformance/packet-decode.json</c> and <c>conformance/replay-window.json</c> — the
/// same files the Rust, Kotlin and Swift suites read. Both are GENERATED by the Rust canon
/// (<c>qeli/src/gen_conformance_main.rs</c>).
///
/// WHY: the record format and the anti-replay window are reimplemented from scratch in four
/// languages. Decoding is deterministic given (key, record), so it pins with no test seam;
/// the window is pure state, so it pins as a table of verdicts. Before these files, nothing
/// compared the four — which is how M6 (the data-plane nonce) shipped in three of them.
/// </summary>
public static class WireConformance
{
    /// <summary>
    /// Run both fixtures, reporting each assertion through <paramref name="check"/>.
    ///
    /// A missing fixture file is a SKIP (a shipped app has no repository next to it) —
    /// except under <c>QELI_CONFORMANCE_REQUIRED=1</c>, which CI sets so a file that moved
    /// cannot turn the gate into a silent no-op.
    /// </summary>
    public static bool Run(Action<string, bool> check)
    {
        bool ok = RunDecode(check);
        ok &= RunReplay(check);
        ok &= RunHkdf(check);
        ok &= RunQuic(check);
        ok &= RunUdpFrag(check);
        ok &= RunCtrlFrame(check);
        ok &= RunMtuLadder(check);
        ok &= RunIniBounds(check);
        return ok;
    }

    /// <summary>Range checks on the hand-writable flat INI. Not fixture-driven — these are
    /// policy, and the failure they guard is silent: an out-of-range value that parses.</summary>
    private static bool RunIniBounds(Action<string, bool> check)
    {
        static Model.VpnConfig Ini(params string[] extra) =>
            Model.VpnConfig.FromIni("[qeli]\nserver = 1.2.3.4:443\nuser = u\npass = p\n"
                                    + string.Join("\n", extra) + "\n");

        // A timeout above ~2.1M seconds used to survive parsing, then overflow the int
        // multiply in VpnTunnelBase (`(int)secs * 1000`) into a NEGATIVE timeout — an
        // instantly-expired connect rather than a long one.
        var huge = Ini("timeout = 999999999");
        bool timeoutClamped = huge.ConnectionTimeoutSecs is >= 1 and <= 300;
        bool noOverflow = (int)huge.ConnectionTimeoutSecs * 1000 > 0;
        check("ini-bounds: an absurd timeout is clamped into range", timeoutClamped);
        check("ini-bounds: the clamped timeout cannot overflow to a negative ms value", noOverflow);
        bool zeroTimeout = Ini("timeout = 0").ConnectionTimeoutSecs == 30;
        bool negTimeout = Ini("timeout = -5").ConnectionTimeoutSecs == 30;
        check("ini-bounds: a zero/negative timeout falls back to the default", zeroTimeout && negTimeout);
        bool sane = Ini("timeout = 45").ConnectionTimeoutSecs == 45;
        check("ini-bounds: a valid timeout is left alone", sane);

        // padding_min > padding_max is an inverted range; a five-digit padding is past the
        // ceiling. Each field only checked `>= 0` on its own, so both parsed.
        var inverted = Ini("padding_min = 900", "padding_max = 300");
        bool ordered = inverted.PaddingMin <= inverted.PaddingMax;
        var over = Ini("padding_min = 0", "padding_max = 60000");
        bool capped = over.PaddingMax <= 1400;
        check("ini-bounds: an inverted padding range is corrected", ordered);
        check("ini-bounds: padding is capped at the ceiling", capped);
        var keep = Ini("padding_min = 10", "padding_max = 200");
        bool kept = keep.PaddingMin == 10 && keep.PaddingMax == 200;
        check("ini-bounds: a valid padding range is left alone", kept);

        // A boolean nobody could parse must NOT read as false. Every unknown value used to be
        // falsey, so `kill_switch = ture` silently disabled the kill switch and
        // `bind_static = ture` silently dropped the static-key binding. Parsing still succeeds
        // (an editor must be able to open a bad profile to fix it); Validate() refuses.
        bool recorded = true, notFalsey = true, refuses = true;
        foreach (var key in new[] { "gateway", "bind_static", "kill_switch", "reconnect", "quic" })
        {
            var c = Ini($"{key} = ture");
            recorded &= c.UnparsedBooleanKeys.Contains(key);
            try { c.Validate(); refuses = false; } catch (ArgumentException) { }
        }
        // The two settings whose default is ON: a typo must leave them ON (and be refused by
        // Validate), never flip them off. `kill_switch` defaults to OFF, so it has nothing to
        // assert here beyond the refusal above — an assertion that it "stayed false" would pass
        // whether or not the fix exists.
        notFalsey &= Ini("bind_static = ture").BindStaticToSession;   // not silently off
        notFalsey &= Ini("gateway = ture").AddDefaultGateway;         // not silently split-tunnel
        check("ini-bools: a typo is recorded, not resolved", recorded);
        check("ini-bools: a typo does not silently disable a security setting", notFalsey);
        check("ini-bools: Validate() refuses a config with an unparseable boolean", refuses);

        // Every spelling the Rust client accepts must still work, both ways.
        bool spellings = true;
        foreach (var yes in new[] { "true", "1", "yes", "on", "TRUE", "On" })
            spellings &= Ini($"quic = {yes}").QuicEnabled;
        foreach (var no in new[] { "false", "0", "no", "off", "FALSE", "Off" })
            spellings &= !Ini($"quic = {no}").QuicEnabled;
        check("ini-bools: every accepted spelling still parses, both ways", spellings);

        // A key written twice must be REFUSED, not silently resolved. The ports disagreed on
        // which line wins: this parser folds entries into a dictionary and keeps the LAST,
        // while the Rust client (config/format.rs Section::get) takes the FIRST — so two
        // `server` lines sent the Rust client to one host and every GUI client to another, out
        // of one file, with nothing reported. Parsing still succeeds (an editor must be able to
        // open the file to fix it); Validate() refuses. (Audit 2026-08-01, §7.)
        var dup = Ini("server = other.example.com:8443");
        bool dupRecorded = dup.DuplicateKeys.Contains("server");
        bool dupRefused = false;
        // The message must name the key, so this cannot pass because Validate() happened to
        // dislike something else about the fixture.
        try { dup.Validate(); } catch (ArgumentException e) { dupRefused = e.Message.Contains("server"); }
        // Recorded ONCE however many times it repeats, and the last value still wins, so a file
        // that already had a duplicate parses exactly as it always did.
        var thrice = Ini("mtu = 1400", "mtu = 1300", "mtu = 1200");
        bool dupOnce = thrice.DuplicateKeys.Count == 1 && thrice.Mtu == 1200;
        // A clean config must record nothing — otherwise the check above passes vacuously.
        bool cleanQuiet = Ini("mtu = 1400").DuplicateKeys.Count == 0;
        check("ini-dups: a key written twice is recorded", dupRecorded);
        check("ini-dups: Validate() refuses an ambiguous config", dupRefused);
        check("ini-dups: recorded once, last value still wins", dupOnce);
        check("ini-dups: a clean config records nothing", cleanQuiet);

        // A number nobody could parse must not become a default in silence. `server =
        // host:notnum` became `host:443` — a DIFFERENT server — with nothing reported, the same
        // failure mode the boolean handling already fixed. (Audit 2026-08-01, §P2.)
        var badPort = Model.VpnConfig.FromIni("[qeli]\nserver = 1.2.3.4:notnum\nuser = u\npass = p\n");
        bool portRecorded = badPort.UnparsedNumericKeys.Count > 0;
        bool portRefused = false;
        try { badPort.Validate(); } catch (ArgumentException) { portRefused = true; }
        // Out of range is as wrong as unparseable — `:0` and `:99999` are not ports.
        bool rangeRecorded =
            Model.VpnConfig.FromIni("[qeli]\nserver = 1.2.3.4:0\nuser = u\npass = p\n")
                .UnparsedNumericKeys.Count > 0
            && Model.VpnConfig.FromIni("[qeli]\nserver = 1.2.3.4:99999\nuser = u\npass = p\n")
                .UnparsedNumericKeys.Count > 0;
        // ...and a good config must record nothing, or the checks above pass vacuously.
        bool numQuiet = Ini("padding_min = 10", "padding_max = 200").UnparsedNumericKeys.Count == 0;
        check("ini-nums: an unparseable port is recorded", portRecorded);
        check("ini-nums: Validate() refuses it", portRefused);
        check("ini-nums: an out-of-range port is recorded too", rangeRecorded);
        check("ini-nums: a valid config records nothing", numQuiet);

        // Every numeric field, not just padding: `mtu = abc` used to become auto-MTU, a
        // mistyped timeout became 30 s, a mistyped AWG knob became its default — each one a
        // setting the operator chose and did not get. (Audit 2026-08-01, §8.)
        bool everyNumericRecorded = true;
        foreach (var key in new[] { "mtu", "timeout", "lport", "metric", "jc", "jmin", "jmax",
                                    "reconnect_retries", "reconnect_base_delay",
                                    "reconnect_max_delay", "heartbeat_interval", "heartbeat_size",
                                    "heartbeat_jitter", "shaping_gap_mean", "shaping_budget",
                                    "shaping_min_size", "shaping_max_size", "shaping_stealth_mbps" })
        {
            everyNumericRecorded &= Ini($"{key} = abc").UnparsedNumericKeys.Contains(key);
        }
        // ...while a value that is merely OUT OF RANGE still falls back silently. That is a
        // documented clamp, not a mistake, and conflating the two would start rejecting
        // configs that have always been accepted.
        var outOfRange = Ini("lport = 99999", "heartbeat_interval = -5");
        bool rangeStillSilent = outOfRange.UnparsedNumericKeys.Count == 0
            && outOfRange.LocalPort == 0 && outOfRange.HeartbeatIntervalMs == 15000;
        check("ini-nums: every numeric field records an unreadable value", everyNumericRecorded);
        check("ini-nums: out-of-range still falls back silently", rangeStillSilent);

        // A MISSPELLED key name is invisible: nothing reads it, so the setting it was meant to
        // change silently keeps its default — `gatway = true` left the tunnel split with
        // nothing said anywhere. The Rust client has always refused these; this port did not.
        // (Audit 2026-08-01, §14.)
        var typo = Ini("gatway = true");
        bool typoRecorded = typo.UnknownKeys.Contains("gatway");
        bool typoRefused = false;
        try { typo.Validate(); } catch (ArgumentException e) { typoRefused = e.Message.Contains("gatway"); }

        // ...but a key another PORT understands is not a typo. `keepalive`, `post_up` and
        // friends are real Rust-client settings, and a desktop profile carrying them must
        // still open here — refusing them would be a worse regression than the typo.
        bool foreignKeysAccepted = true;
        foreach (var k in new[] { "keepalive = 25", "post_up = /bin/true", "exit_node = true",
                                  "lan_subnet = 10.0.0.0/24", "tcp_nodelay = true" })
        {
            var c = Ini(k);
            foreignKeysAccepted &= c.UnknownKeys.Count == 0;
        }

        // The strongest guard against a wrong list: everything this port WRITES must be
        // something it accepts back. A key added to ToIni without KnownIniKeys would make the
        // client refuse its own saved profile, so that failure shows up here instead.
        var full = new Model.VpnConfig
        {
            ServerAddress = "h", Port = 443, WireMode = "obfs", ObfsKey = "k",
            ObfsFronting = "none", Protocol = "udp", QuicEnabled = true, Sni = "www.example.com",
            RealityShortId = "abcdef01", Mtu = 1400, DnsServers = new List<string> { "1.1.1.1" },
        };
        var roundTripped = Model.VpnConfig.FromIni(full.ToIni());
        bool roundTripClean = roundTripped.UnknownKeys.Count == 0;
        check("ini-unknown: a misspelled key is recorded", typoRecorded);
        check("ini-unknown: Validate() refuses it", typoRefused);
        check("ini-unknown: keys other ports own are NOT typos", foreignKeysAccepted);
        check("ini-unknown: everything ToIni writes is accepted back", roundTripClean);

        // The enum checks the desktop client had no equivalent of at all.
        bool enums = true;
        foreach (var (line, _) in new[] { ("proto = ucp", 0), ("mode = realty-tls", 0), ("front = webscoket", 0) })
        {
            try { Ini(line).Validate(); enums = false; } catch (ArgumentException) { }
        }
        try { Ini("proto = udp").Validate(); } catch (ArgumentException) { enums = false; }
        check("ini-bools: unknown proto/mode/front are refused, valid ones accepted", enums);

        return timeoutClamped && noOverflow && zeroTimeout && negTimeout && sane
               && ordered && capped && kept
               && recorded && notFalsey && refuses && spellings && enums;
    }

    /// <summary>The path-MTU ladder's floor. Not fixture-driven — it is a policy, not a wire
    /// format. What this catches is the rung/path unit confusion (#12): rungs are INNER tunnel
    /// MTUs, 1280 is an OUTER path limit, so a floor of 1280 asks a 1280-byte path for
    /// 1280 + overhead and every rung fails on exactly the narrow paths probing exists for.</summary>
    private static bool RunMtuLadder(Action<string, bool> check)
    {
        // Both extremes this codebase actually produces: bare IPv4 UDP, and the worst case of
        // obfs seal (13) + QUIC short header (9) + UDP (8) + IPv6 (40), each over a 48-byte record.
        bool floorFits = true, descending = true, nonEmpty = true;
        foreach (int overhead in new[] { 48 + 8 + 20, 48 + 13 + 9 + 8 + 40 })
        {
            var ladder = Vpn.VpnTunnelBase.MtuProbeLadder(1400, overhead);
            nonEmpty &= ladder.Length > 0;
            if (ladder.Length == 0) continue;
            // The narrowest rung's WIRE size must fit a 1280-byte path.
            floorFits &= ladder[^1] + overhead <= 1280;
            for (int i = 1; i < ladder.Length; i++) descending &= ladder[i] < ladder[i - 1];
        }
        check("mtu-ladder: ladder is never empty", nonEmpty);
        check("mtu-ladder: lowest rung fits a 1280-byte path once framing is counted", floorFits);
        check("mtu-ladder: rungs are strictly descending and deduped", descending);

        // A ceiling already below the floor must still yield something to try, not an empty
        // ladder (which would report "no result" and silently keep the pushed MTU).
        var tiny = Vpn.VpnTunnelBase.MtuProbeLadder(700, 48 + 13 + 9 + 8 + 40);
        check("mtu-ladder: a low ceiling still produces a rung", tiny.Length > 0 && tiny[0] <= 700);

        // A JUMBO ceiling must not fall straight to 1360. The ladder was written when the
        // ceiling was an Ethernet-sized number, so the rung below it was 1360 and the gap was
        // 140 bytes; raising the ceiling to 16638 turned that gap into 15278, and a path
        // carrying 9000 was certified at 1360. (Audit 2026-08-01, §8.)
        int jumboOverhead = 48 + 13 + 9 + 8 + 40;
        var jumbo = Vpn.VpnTunnelBase.MtuProbeLadder(16638, jumboOverhead);
        bool hasMiddle = jumbo.Count(m => m >= 1360 && m < 16638) >= 3;
        int under9000 = jumbo.FirstOrDefault(m => m + jumboOverhead <= 9000);
        bool jumboUseful = under9000 >= 4000;
        check("mtu-ladder: a jumbo ceiling has rungs between it and 1360", hasMiddle);
        check("mtu-ladder: a 9000-byte path certifies near 9000, not 1360", jumboUseful);
        // ...and a normal path is probed exactly as before, so the jumbo rungs cost no extra
        // round-trips for the common case.
        bool normalUnchanged = Vpn.VpnTunnelBase.MtuProbeLadder(1400, jumboOverhead)
            .SequenceEqual(new[] { 1400, 1360, 1320, 1280, 1200, 1280 - jumboOverhead });
        check("mtu-ladder: a normal ceiling gains no extra rungs", normalUnchanged);

        // Refinement finds the path's REAL MTU, not just the best rung that fits. A ladder can
        // only land on its own numbers, so adding rungs moves the loss around instead of
        // removing it: with rungs at 9000 and 6000 an 8999-byte path was pinned to 6000.
        // Same search as the probe loop, driven against a simulated path.
        // (Audit 2026-08-01, §8.)
        static (int Result, int Probes) Search(int lo, int hi, int real)
        {
            int probes = 0;
            for (int i = 0; i < Vpn.VpnTunnelBase.MtuRefineMaxProbes; i++)
            {
                int mid = Vpn.VpnTunnelBase.MtuRefineStep(lo, hi);
                if (mid < 0) break;
                probes++;
                if (mid <= real) lo = mid; else hi = mid;
            }
            return (lo, probes);
        }
        bool converges = true, neverOver = true, bounded = true;
        foreach (var (lo0, hi0, real) in new[] { (6000, 9000, 8999), (4000, 6000, 5500), (1500, 2500, 2000) })
        {
            var (got, probes) = Search(lo0, hi0, real);
            neverOver &= got <= real;
            converges &= real - got <= Vpn.VpnTunnelBase.MtuRefineStepBytes && got > lo0;
            bounded &= probes <= Vpn.VpnTunnelBase.MtuRefineMaxProbes;
        }
        // A path barely above the rung must not be made worse, and a narrow bracket must stop.
        var (atRung, _) = Search(6000, 9000, 6001);
        check("mtu-refine: converges to within one step of the real path MTU", converges);
        check("mtu-refine: never certifies above what the path carries", neverOver && atRung == 6000);
        check("mtu-refine: probe budget is bounded", bounded && Vpn.VpnTunnelBase.MtuRefineStep(6000, 6200) < 0);
        normalUnchanged &= converges && neverOver && bounded;

        return floorFits && descending && nonEmpty && tiny.Length > 0
            && hasMiddle && jumboUseful && normalUnchanged;
    }

    /// <summary>In-tunnel control frames. Not fixture-driven — the frame is six bytes, so the
    /// bytes themselves are pinned here and in the Rust/Kotlin/Swift tests. What this catches is
    /// a port drifting on byte order or on the magic, which would make the server read a
    /// nonsense MTU (or route the frame as a packet).</summary>
    private static bool RunCtrlFrame(Action<string, bool> check)
    {
        // 1280 = 0x0500, big-endian. Same vector in every implementation.
        var expected = new byte[] { 0xC1, 0x9B, 0x01, 0x02, 0x05, 0x00 };
        bool ok = Hex(CtrlFrame.MtuReport(1280)) == Hex(expected);
        check("ctrl: MtuReport(1280) matches the shared vector", ok);

        // The discriminator that keeps control frames and IP packets apart, in both directions.
        bool disjoint = CtrlFrame.IsCtrl(expected)
            && !CtrlFrame.IsCtrl(new byte[] { 0x45, 0x00, 0x00, 0x28 })   // IPv4
            && !CtrlFrame.IsCtrl(new byte[] { 0x60, 0x00, 0x00, 0x00 })   // IPv6
            && !CtrlFrame.IsCtrl(System.Array.Empty<byte>());             // heartbeat
        check("ctrl: frames and IP packets cannot be confused", disjoint);

        // Out-of-range values are clamped, never wrapped into a plausible small MTU.
        bool clamped = Hex(CtrlFrame.MtuReport(70_000)) == "c19b0102ffff"
            && Hex(CtrlFrame.MtuReport(-1)) == "c19b01020000";
        check("ctrl: out-of-range MTU is clamped, not wrapped", clamped);

        // Client info (#2). The SAME vector the Rust test pins, so the four implementations
        // cannot drift: `[magic][type=2][len=12][ver_len=6]["0.7.13"]["linux"]`.
        bool info = Hex(CtrlFrame.ClientInfo("0.7.13", "linux")!) == "c19b020c06302e372e31336c696e7578";
        check("ctrl: ClientInfo(0.7.13, linux) matches the shared vector", info);

        // The server REJECTS a bad version or platform outright rather than scrubbing it, so a
        // frame it would refuse must not be built here either — otherwise the client reports
        // nothing and has no way to know why. These are the shapes that reach a log line, a
        // terminal table and the panel's DOM.
        bool refused =
            CtrlFrame.ClientInfo("0.7.13\nX", "linux") == null      // newline forges a log line
            && CtrlFrame.ClientInfo("<b>1.0</b>", "linux") == null   // markup reaches the panel DOM
            && CtrlFrame.ClientInfo("", "linux") == null             // empty
            && CtrlFrame.ClientInfo(new string('9', 33), "linux") == null   // over the 32-byte cap
            && CtrlFrame.ClientInfo("0.7.13", "Linux") == null       // platform must be lowercase
            && CtrlFrame.ClientInfo("0.7.13", "") == null
            && CtrlFrame.ClientInfo("0.7.13", new string('a', 17)) == null; // over the 16-byte cap
        check("ctrl: an unrepresentable version/platform yields no frame", refused);

        // Valid non-trivial values must still build: a real pre-release version, every platform
        // tag the closed set allows.
        bool accepted = CtrlFrame.ClientInfo("1.0.0-rc1+build.7", "linux") != null
            && new[] { "linux", "windows", "macos", "android", "ios", "freebsd", "other" }
                .All(pl => CtrlFrame.ClientInfo("0.7.13", pl) != null);
        check("ctrl: real versions and every platform tag are accepted", accepted);

        // This build must actually produce a frame — a null here means every session shows as
        // unknown, which is the failure the feature exists to remove.
        bool self = CtrlFrame.ThisBuild() != null && CtrlFrame.ClientInfo("0.7.13", CtrlFrame.PlatformTag()) != null;
        check("ctrl: this build reports a usable version and platform", self);

        return ok && disjoint && clamped && info && refused && accepted && self;
    }

    /// <summary>App-layer fragmentation of the big UDP handshake messages. The reassembler is
    /// fed by the NETWORK — out of order, with duplicates, with gaps, and with whatever an
    /// attacker sends — so the malformed cases matter as much as the happy ones. The failure
    /// this pins against is a handshake that hangs only on LTE.</summary>
    private static bool RunUdpFrag(Action<string, bool> check)
    {
        var root = Load("udp-frag.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "udp-frag", check)) return false;

            check("udp-frag: fixture MaxChunk matches this build",
                r.GetProperty("max_chunk").GetInt32() == UdpFrag.MaxChunk);
            // The receive bound is pinned separately and is LARGER: bounding receive by the
            // send budget would reject every handshake from a pre-#14 peer.
            check("udp-frag: fixture MaxChunkAccept matches this build",
                r.GetProperty("max_chunk_accept").GetInt32() == UdpFrag.MaxChunkAccept);
            check("udp-frag: fixture MaxFrags matches this build",
                r.GetProperty("max_frags").GetInt32() == UdpFrag.MaxFrags);
            check("udp-frag: a legacy 1200-byte chunk still reassembles", LegacyChunkAccepted());

            int n = 0;
            foreach (var c in r.GetProperty("fragment").EnumerateArray())
            {
                n++;
                string name = c.GetProperty("name").GetString() ?? "?";
                byte msgId = (byte)c.GetProperty("msg_id").GetInt32();
                var expect = c.GetProperty("expect");

                if (expect.TryGetProperty("reject", out var rej) && rej.GetBoolean())
                {
                    // The oversize body is megabytes, so the fixture records its SHAPE.
                    int len = c.GetProperty("message_len").GetInt32();
                    var big = new byte[len];
                    for (int i = 0; i < len; i++) big[i] = (byte)((i * 31 + 7) % 256);
                    bool refused;
                    try { UdpFrag.Fragment(msgId, big); refused = false; }
                    catch { refused = true; }
                    check($"udp-frag[{name}]: oversize message refused at the sender", refused);
                }
                else
                {
                    var msg = Convert.FromHexString(c.GetProperty("message").GetString()!);
                    var got = UdpFrag.Fragment(msgId, msg).Select(Hex).ToList();
                    var want = expect.GetProperty("fragments").EnumerateArray()
                        .Select(f => f.GetString()!).ToList();
                    check($"udp-frag[{name}]: fragments", got.SequenceEqual(want));
                }
            }

            foreach (var c in r.GetProperty("reassemble").EnumerateArray())
            {
                n++;
                string name = c.GetProperty("name").GetString() ?? "?";
                var expect = c.GetProperty("expect");

                // A FRESH reassembler per case.
                var re = new UdpFrag.Reassembler();
                byte[]? completed = null;
                bool rejected = false;
                foreach (var d in c.GetProperty("feed").EnumerateArray())
                {
                    try
                    {
                        var got = re.Push(Convert.FromHexString(d.GetString()!));
                        if (got != null) { completed = got; break; }
                    }
                    catch { rejected = true; break; }
                }

                if (expect.TryGetProperty("reject", out var rej) && rej.GetBoolean())
                    check($"udp-frag[{name}]: malformed fragment rejected", rejected);
                else if (expect.TryGetProperty("incomplete", out var inc) && inc.GetBoolean())
                    check($"udp-frag[{name}]: stays incomplete", !rejected && completed == null);
                else
                    check($"udp-frag[{name}]: reassembled message",
                        completed != null && Hex(completed) == expect.GetProperty("message").GetString());
            }

            foreach (var c in r.GetProperty("classify").EnumerateArray())
            {
                n++;
                string name = c.GetProperty("name").GetString() ?? "?";
                var d = Convert.FromHexString(c.GetProperty("datagram").GetString()!);
                var e = c.GetProperty("expect");
                bool ok = UdpFrag.IsFragment(d) == e.GetProperty("is_fragment").GetBoolean()
                       && UdpFrag.IsJunk(d) == e.GetProperty("is_junk").GetBoolean()
                       && UdpFrag.IsMtuProbe(d) == e.GetProperty("is_mtu_probe").GetBoolean()
                       && UdpFrag.IsMtuProbeAck(d) == e.GetProperty("is_mtu_probe_ack").GetBoolean();
                check($"udp-frag[{name}]: classification", ok);
            }

            check($"udp-frag: {n} case(s) ran", n > 0);
            return n > 0;
        }
    }

    /// <summary>The four directional key-derivation schemes. Both ends must derive
    /// byte-identical keys or the tunnel does not come up; a subtler divergence — the two
    /// DIRECTIONS swapped — yields a tunnel that authenticates and then decrypts nothing.</summary>
    private static bool RunHkdf(Action<string, bool> check)
    {
        var root = Load("hkdf.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "hkdf", check)) return false;

            int cases = 0;
            foreach (var c in r.GetProperty("cases").EnumerateArray())
            {
                cases++;
                string name = c.GetProperty("name").GetString() ?? "?";
                var inp = c.GetProperty("inputs");
                byte[] In(string k) => Convert.FromHexString(inp.GetProperty(k).GetString()!);

                (byte[] s2c, byte[] c2s) keys = c.GetProperty("scheme").GetString() switch
                {
                    "classic" => Crypto.KeyDerivation.DeriveKeys(In("shared_secret")),
                    "hybrid" => Crypto.KeyDerivation.DeriveKeysHybrid(In("x25519_shared"), In("mlkem_shared")),
                    "bound" => Crypto.KeyDerivation.DeriveKeysBound(In("ee"), In("es")),
                    "hybrid-bound" => Crypto.KeyDerivation.DeriveKeysHybridBound(
                        In("x25519_shared"), In("mlkem_shared"), In("es")),
                    var other => throw new InvalidOperationException($"unknown scheme `{other}`"),
                };

                var expect = c.GetProperty("expect");
                check($"hkdf[{name}]: server_to_client",
                    Hex(keys.s2c) == expect.GetProperty("server_to_client").GetString());
                check($"hkdf[{name}]: client_to_server",
                    Hex(keys.c2s) == expect.GetProperty("client_to_server").GetString());
            }
            check($"hkdf: {cases} case(s) ran", cases > 0);
            return cases > 0;
        }
    }

    /// <summary>QUIC envelope + the crafted packets a parser must survive. The parse half is
    /// attacker-facing: anyone who can send the client a datagram controls those bytes, and a
    /// crafted varint once crashed this very implementation into a reconnect loop.</summary>
    private static bool RunQuic(Action<string, bool> check)
    {
        var root = Load("quic.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "quic", check)) return false;

            int n = 0;
            foreach (var w in r.GetProperty("wrap").EnumerateArray())
            {
                n++;
                string name = w.GetProperty("name").GetString() ?? "?";
                var payload = Convert.FromHexString(w.GetProperty("payload").GetString()!);
                var cid = Convert.FromHexString(w.GetProperty("connection_id").GetString()!);
                // The fixture carries the packet number as an unsigned 32-bit value (Rust and
                // Swift type it that way); this API takes a signed int, so pass the same BIT
                // PATTERN. The wire contract is the four bytes, not the language's idea of sign.
                int pn = unchecked((int)w.GetProperty("packet_number").GetUInt32());

                var packet = Quic.WrapShort(payload, cid, pn);
                check($"quic[{name}]: wrapped packet",
                    Hex(packet) == w.GetProperty("expect").GetProperty("packet").GetString());

                var back = Quic.UnwrapPayload(packet);
                check($"quic[{name}]: payload round-trip",
                    back != null && Hex(back) == Hex(payload));
            }

            foreach (var p in r.GetProperty("parse").EnumerateArray())
            {
                n++;
                string name = p.GetProperty("name").GetString() ?? "?";
                var packet = Convert.FromHexString(p.GetProperty("packet").GetString()!);
                var expect = p.GetProperty("expect");

                // A crafted packet must be rejected CLEANLY — no throw, no hang, no allocation
                // sized from an attacker-supplied length. A throw is a failure here, not a pass.
                byte[]? got;
                try { got = Quic.UnwrapPayload(packet); }
                catch (Exception e)
                {
                    check($"quic[{name}]: crafted packet handled without throwing ({e.GetType().Name})", false);
                    continue;
                }

                if (expect.TryGetProperty("reject", out var rej) && rej.GetBoolean())
                    check($"quic[{name}]: crafted packet rejected", got == null);
                else
                    check($"quic[{name}]: payload",
                        got != null && Hex(got) == expect.GetProperty("payload").GetString());
            }
            check($"quic: {n} case(s) ran", n > 0);
            return n > 0;
        }
    }

    private static bool RunDecode(Action<string, bool> check)
    {
        var root = Load("packet-decode.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "packet-decode", check)) return false;

            int cases = 0;
            foreach (var c in r.GetProperty("cases").EnumerateArray())
            {
                cases++;
                string name = c.GetProperty("name").GetString() ?? "?";
                var key = Convert.FromHexString(c.GetProperty("key").GetString()!);
                var record = Convert.FromHexString(c.GetProperty("record").GetString()!);
                bool raw = c.GetProperty("framing").GetString() == "raw";
                var expect = c.GetProperty("expect");

                // A fresh codec per case: every record carries counter 0, so the cases are
                // independent and a replay rejection can never mask a decode failure.
                var codec = new PacketCodec(new PacketCipher(key), raw: raw);

                if (expect.TryGetProperty("reject", out var rej) && rej.GetBoolean())
                {
                    bool rejected;
                    try { codec.Decrypt(record); rejected = false; }
                    catch { rejected = true; }
                    check($"packet-decode[{name}]: corrupt record rejected", rejected);
                }
                else
                {
                    string want = expect.GetProperty("plaintext").GetString()!;
                    string got;
                    try { got = Convert.ToHexString(codec.Decrypt(record)).ToLowerInvariant(); }
                    catch (Exception e) { got = $"<threw: {e.Message}>"; }
                    check($"packet-decode[{name}]: plaintext", got == want);
                }
            }
            check($"packet-decode: {cases} case(s) ran", cases > 0);
            return cases > 0;
        }
    }

    private static bool RunReplay(Action<string, bool> check)
    {
        var root = Load("replay-window.json", check, out var doc);
        if (doc == null) return root.HasValue;
        using (doc)
        {
            var r = root!.Value;
            if (!RequireListed(r, "replay-window", check)) return false;

            // The fixture was generated for a specific window size; a build with a different
            // one would fail cases for a reason that has nothing to do with correctness.
            if (r.TryGetProperty("window_size", out var ws))
                check("replay-window: fixture window size matches this build",
                    ws.GetInt32() == PacketCodec.ReplayWindow);

            int cases = 0;
            foreach (var c in r.GetProperty("cases").EnumerateArray())
            {
                cases++;
                string name = c.GetProperty("name").GetString() ?? "?";

                // A FRESH window per case. The codec owns the window, so a fresh codec is a
                // fresh window; the key is irrelevant here (no crypto is exercised).
                var codec = new PacketCodec(new PacketCipher(new byte[32]));

                var seqs = c.GetProperty("seqs").EnumerateArray().Select(v => v.GetInt64()).ToList();
                var want = c.GetProperty("verdicts").EnumerateArray().Select(v => v.GetBoolean()).ToList();
                var got = seqs.Select(codec.AcceptCounter).ToList();

                check($"replay-window[{name}]: verdicts", got.SequenceEqual(want));
            }
            check($"replay-window: {cases} case(s) ran", cases > 0);
            return cases > 0;
        }
    }

    private static string Hex(byte[] b) => Convert.ToHexString(b).ToLowerInvariant();

    /// <summary>A pre-#14 peer slices at 1200, which is ABOVE this build's send budget. The
    /// reassembler must bound by MaxChunkAccept, not MaxChunk, or every legacy handshake is
    /// rejected as "fragment chunk too large".</summary>
    private static bool LegacyChunkAccepted()
    {
        // Not `const`: with both sides constant the compiler folds the guard below and warns
        // the failure branch is unreachable (CS0162) — true today, but the guard is the point.
        int legacy = 1200;
        if (legacy <= UdpFrag.MaxChunk) return false;   // the bounds must actually differ
        var re = new UdpFrag.Reassembler();
        try
        {
            for (byte idx = 0; idx < 2; idx++)
            {
                var d = new byte[UdpFrag.HdrLen + legacy];
                System.Array.Copy(UdpFrag.Magic, d, 3);
                d[3] = UdpFrag.MsgServerHello; d[4] = idx; d[5] = 2;
                for (int i = UdpFrag.HdrLen; i < d.Length; i++) d[i] = (byte)'L';
                var done = re.Push(d);
                if (idx == 0 && done != null) return false;
                if (idx == 1) return done != null && done.Length == legacy * 2;
            }
        }
        catch (System.Exception) { return false; }
        return false;
    }

    /// <summary>A platform on the fixture's `platforms` list MUST actually run it — otherwise
    /// a renamed primitive leaves this green having verified nothing.</summary>
    private static bool RequireListed(JsonElement root, string label, Action<string, bool> check)
    {
        bool listed = false;
        if (root.TryGetProperty("platforms", out var platforms))
            foreach (var p in platforms.EnumerateArray())
                if (p.GetString() == "csharp") listed = true;
        check($"{label}: csharp listed in `platforms`", listed);
        return listed;
    }

    /// <summary>Load a fixture, or report a SKIP/failure and return null.</summary>
    private static JsonElement? Load(string file, Action<string, bool> check, out JsonDocument? doc)
    {
        doc = null;
        var path = Find(file);
        if (path == null)
        {
            bool required = Environment.GetEnvironmentVariable("QELI_CONFORMANCE_REQUIRED") == "1";
            check($"wire conformance fixtures found (conformance/{file})", !required);
            if (!required)
                Console.WriteLine($"  [SKIP] {file} — fixtures not found (not running from a source tree)");
            return required ? null : (JsonElement?)default(JsonElement);
        }
        try
        {
            doc = JsonDocument.Parse(File.ReadAllText(path));
            return doc.RootElement;
        }
        catch (Exception e)
        {
            check($"{file} parse ({e.Message})", false);
            return null;
        }
    }

    /// <summary>Walk up from the working directory — the selftest runs from different
    /// directories on Windows and macOS, and a fixed path would silently find nothing.</summary>
    private static string? Find(string file)
    {
        var env = Environment.GetEnvironmentVariable("QELI_CONFORMANCE_FIXTURES_DIR");
        if (!string.IsNullOrEmpty(env))
        {
            var p = Path.Combine(env, file);
            if (File.Exists(p)) return p;
        }
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir != null)
        {
            var candidate = Path.Combine(dir.FullName, "conformance", file);
            if (File.Exists(candidate)) return candidate;
            dir = dir.Parent;
        }
        return null;
    }
}
