package com.qeli.protocol

import com.qeli.crypto.KeyDerivation
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * Key derivation and QUIC masking, checked against the SHARED cross-language fixtures
 * `conformance/hkdf.json` and `conformance/quic.json` — both GENERATED by the Rust canon
 * (`qeli/src/gen_conformance_main.rs`).
 *
 * WHY HKDF: both ends must derive byte-identical keys or the tunnel does not come up, and a
 * subtler divergence — the two DIRECTIONS swapped — yields a tunnel that authenticates and
 * then decrypts nothing. Three of the four schemes take several 32-byte secrets whose ORDER
 * is wire-format.
 *
 * WHY QUIC: the parse half is attacker-facing — anyone who can send this client a datagram
 * controls those bytes, and a crafted varint once crashed this very implementation into a
 * reconnect loop while Rust was already safe.
 */
class CryptoConformanceTest {

    private fun hex(b: ByteArray): String = b.joinToString("") { "%02x".format(it) }

    private fun unhex(s: String): ByteArray {
        require(s.length % 2 == 0) { "odd-length hex string: $s" }
        return ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
    }

    private fun fixture(name: String): JSONObject {
        var dir: File? = File("").absoluteFile
        while (dir != null) {
            val f = File(dir, "conformance/$name")
            if (f.isFile) return JSONObject(f.readText())
            dir = dir.parentFile
        }
        fail("conformance/$name not found walking up from ${File("").absolutePath}")
        error("unreachable")
    }

    private fun requireListed(fx: JSONObject, label: String) {
        val p = fx.getJSONArray("platforms")
        val listed = (0 until p.length()).map { p.getString(it) }
        assertTrue("kotlin is not listed in `platforms` of $label", listed.contains("kotlin"))
    }

    @Test
    fun `derives every shared key vector`() {
        val fx = fixture("hkdf.json")
        requireListed(fx, "hkdf.json")

        val cases = fx.getJSONArray("cases")
        assertTrue("fixture file has no cases", cases.length() > 0)

        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val inp = c.getJSONObject("inputs")
            fun input(k: String) = unhex(inp.getString(k))

            val keys = when (val scheme = c.getString("scheme")) {
                "classic" -> KeyDerivation.deriveKeys(input("shared_secret"))
                "hybrid" -> KeyDerivation.deriveKeysHybrid(input("x25519_shared"), input("mlkem_shared"))
                "bound" -> KeyDerivation.deriveKeysBound(input("ee"), input("es"))
                "hybrid-bound" -> KeyDerivation.deriveKeysHybridBound(
                    input("x25519_shared"), input("mlkem_shared"), input("es")
                )
                else -> throw IllegalStateException("case $name: unknown scheme `$scheme`")
            }

            val expect = c.getJSONObject("expect")
            assertEquals("case $name: server_to_client", expect.getString("server_to_client"), hex(keys.first))
            assertEquals("case $name: client_to_server", expect.getString("client_to_server"), hex(keys.second))
        }
    }

    @Test
    fun `masks and parses every shared QUIC vector`() {
        val fx = fixture("quic.json")
        requireListed(fx, "quic.json")

        val wraps = fx.getJSONArray("wrap")
        assertTrue("fixture has no wrap cases", wraps.length() > 0)
        for (i in 0 until wraps.length()) {
            val w = wraps.getJSONObject(i)
            val name = w.getString("name")
            val payload = unhex(w.getString("payload"))
            val cid = unhex(w.getString("connection_id"))
            // The fixture carries the packet number as an UNSIGNED 32-bit value (Rust and Swift
            // type it that way); this API takes a signed Int, so pass the same BIT PATTERN. The
            // wire contract is the four bytes, not the language's idea of sign.
            val pn = w.getLong("packet_number").toInt()

            val packet = Quic.wrapShort(payload, cid, pn)
            assertEquals("case $name: wrapped packet",
                w.getJSONObject("expect").getString("packet"), hex(packet))

            val back = Quic.unwrapPayload(packet)
            assertNotNull("case $name: own output failed to parse", back)
            assertEquals("case $name: payload round-trip", hex(payload), hex(back!!))
        }

        val parses = fx.getJSONArray("parse")
        assertTrue("fixture has no parse cases", parses.length() > 0)
        for (i in 0 until parses.length()) {
            val p = parses.getJSONObject(i)
            val name = p.getString("name")
            val packet = unhex(p.getString("packet"))
            val expect = p.getJSONObject("expect")

            // A crafted packet must be rejected CLEANLY — returning null, not throwing and not
            // allocating from an attacker-supplied length. A throw is a failure here, not a pass.
            val got = try {
                Quic.unwrapPayload(packet)
            } catch (e: Exception) {
                fail("case $name: crafted packet threw ${e::class.simpleName} instead of being rejected")
                null
            }

            if (expect.optBoolean("reject", false)) {
                assertNull("case $name: a crafted packet was ACCEPTED", got)
            } else {
                assertNotNull("case $name: a valid packet was rejected", got)
                assertEquals("case $name: payload", expect.getString("payload"), hex(got!!))
            }
        }
    }
}
