package com.qeli.protocol

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * M6 — data-plane nonce derivation, checked against the SHARED cross-language fixture
 * `conformance/prp-nonce.json` (generated by the Rust canon, see
 * `qeli/src/gen_conformance_main.rs`).
 *
 * WHY THIS FILE EXISTS: the M6 fix (counter-derived PRP nonce replacing a random 96-bit
 * nonce) was ported to Rust, C# and Swift but silently MISSED on Android — the whole TX
 * path kept generating random nonces, carrying the birthday-collision risk the design
 * removes. Nothing caught it because there was no PacketCodec test here at all, and the
 * only cross-language fixture at the time (qeli-links.json) covers link parsing, not the
 * wire codec.
 *
 * Interop note: the nonce travels on the wire and the receiver never inverts the PRP, so
 * the transform is one-sided — the peer does not need the same key. The fixture supplies
 * the key as an explicit input and pins the FUNCTION.
 */
class PacketCodecNonceTest {

    private fun hex(b: ByteArray): String = b.joinToString("") { "%02x".format(it) }

    private fun unhex(s: String): ByteArray {
        require(s.length % 2 == 0) { "odd-length hex string: $s" }
        return ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
    }

    /**
     * The fixture lives outside the Gradle module, so resolve it by walking up from the
     * working directory instead of hardcoding a depth — the test must fail loudly if the
     * file moves, never silently pass by testing nothing.
     */
    private fun fixtures(): JSONObject {
        var dir: File? = File("").absoluteFile
        while (dir != null) {
            val f = File(dir, "conformance/prp-nonce.json")
            if (f.isFile) return JSONObject(f.readText())
            dir = dir.parentFile
        }
        fail("conformance/prp-nonce.json not found walking up from ${File("").absolutePath}")
        error("unreachable")
    }

    @Test
    fun `matches the shared cross-language vectors`() {
        val fx = fixtures()

        // A platform listed in the fixture MUST actually run it. Without this a renamed
        // primitive or a moved file could leave this test green having verified nothing —
        // the exact failure mode the fixtures exist to prevent.
        val platforms = fx.getJSONArray("platforms")
        val listed = (0 until platforms.length()).map { platforms.getString(it) }
        assertTrue("kotlin is not listed in `platforms` of prp-nonce.json", listed.contains("kotlin"))

        val cases = fx.getJSONArray("cases")
        assertTrue("fixture file has no cases", cases.length() > 0)

        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val key = unhex(c.getString("key"))
            val seed = unhex(c.getString("seed"))
            val counter = c.getLong("counter")

            // Rebuild `raw` from seed+counter rather than trusting the field: this pins the
            // seed‖counter_be LAYOUT independently of the permutation. A port can be right
            // about the Feistel network and wrong about what it permutes.
            val raw = PacketCodec.rawNonce(seed, counter)
            assertEquals("case $name: raw nonce layout (seed || counter_be)",
                c.getString("raw"), hex(raw))

            assertEquals("case $name: permuted nonce",
                c.getString("nonce"), hex(PacketCodec.prpNonce(key, raw)))
        }
    }

    /**
     * The security property M6 buys: a balanced Feistel network is bijective for ANY round
     * function, so distinct (seed,counter) inputs — the counter is monotonic — can never
     * collide. A random 96-bit nonce (the pre-fix Android behaviour) only gets this
     * probabilistically, which is exactly the birthday risk being removed.
     *
     * Not in the fixture because it is a property over 100k inputs, not a table of vectors.
     */
    @Test
    fun `distinct counters never collide`() {
        val key = ByteArray(32) { it.toByte() }
        val seed = byteArrayOf(0xAA.toByte(), 0xBB.toByte(), 0xCC.toByte(), 0xDD.toByte())
        val n = 100_000
        val seen = HashSet<String>(n * 2)
        for (c in 0 until n) {
            seen.add(hex(PacketCodec.prpNonce(key, PacketCodec.rawNonce(seed, c.toLong()))))
        }
        assertEquals("all $n nonces must be distinct", n, seen.size)
    }

    /**
     * The DPI property: the on-wire nonce must NOT be the visible "+1 per packet" counter.
     */
    @Test
    fun `destroys the visible counter pattern`() {
        val key = ByteArray(32) { it.toByte() }
        val seed = byteArrayOf(0xAA.toByte(), 0xBB.toByte(), 0xCC.toByte(), 0xDD.toByte())
        val n0 = PacketCodec.prpNonce(key, PacketCodec.rawNonce(seed, 0L))
        val n1 = PacketCodec.prpNonce(key, PacketCodec.rawNonce(seed, 1L))
        assertNotEquals("permuted nonce must not equal the raw counter input",
            hex(PacketCodec.rawNonce(seed, 0L)), hex(n0))
        val differingBytes = n0.indices.count { n0[it] != n1[it] }
        assertTrue("consecutive nonces must differ broadly, got $differingBytes/12 bytes",
            differingBytes >= 6)
        assertNotEquals("the seed must not survive verbatim into the output",
            "aabbccdd", hex(n0).substring(0, 8))
    }
}
