package com.qeli.protocol

import com.qeli.crypto.PacketCipher
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * Wire-codec conformance against the SHARED cross-language fixtures
 * `conformance/packet-decode.json` and `conformance/replay-window.json`, both GENERATED by
 * the Rust canon (`qeli/src/gen_conformance_main.rs`).
 *
 * WHY: the record format and the anti-replay window are reimplemented from scratch in four
 * languages. Decoding is deterministic given (key, record), so it pins with no test seam;
 * the window is pure state, so it pins as a table of verdicts. Before these fixtures nothing
 * compared the four implementations — which is how the M6 nonce fix shipped in three of them
 * and silently skipped Android.
 *
 * These tests run on the JVM (not a device); `unitTests.isReturnDefaultValues` in
 * build.gradle.kts is what makes the codec constructible here at all, since PacketCipher
 * touches android.util.Log at class-init.
 */
class WireConformanceTest {

    private fun hex(b: ByteArray): String = b.joinToString("") { "%02x".format(it) }

    private fun unhex(s: String): ByteArray {
        require(s.length % 2 == 0) { "odd-length hex string: $s" }
        return ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
    }

    /** Walk up from the working directory — the fixtures live outside the Gradle module. */
    private fun fixture(name: String): JSONObject {
        var dir: File? = File("").absoluteFile
        while (dir != null) {
            val f = File(dir, "conformance/$name")
            if (f.isFile) return JSONObject(f.readText())
            dir = dir.parentFile
        }
        fail("conformance/$name not found walking up from ${File("").absolutePath}")
        error("unreachable")
    }

    /** A platform listed in the fixture MUST run it — a green test that skipped is the
     *  failure these fixtures exist to prevent. */
    private fun requireListed(fx: JSONObject, label: String) {
        val p = fx.getJSONArray("platforms")
        val listed = (0 until p.length()).map { p.getString(it) }
        assertTrue("kotlin is not listed in `platforms` of $label", listed.contains("kotlin"))
    }

    @Test
    fun `decodes every shared record vector`() {
        val fx = fixture("packet-decode.json")
        requireListed(fx, "packet-decode.json")

        val cases = fx.getJSONArray("cases")
        assertTrue("fixture file has no cases", cases.length() > 0)

        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val key = unhex(c.getString("key"))
            val record = unhex(c.getString("record"))
            val raw = c.getString("framing") == "raw"
            val expect = c.getJSONObject("expect")

            // A fresh codec per case: every record carries counter 0, so the cases are
            // independent and a replay rejection can never mask a decode failure.
            val codec = PacketCodec(PacketCipher(key), raw = raw)

            if (expect.optBoolean("reject", false)) {
                val rejected = try {
                    codec.decrypt(record); false
                } catch (_: Exception) {
                    true
                }
                assertTrue("case $name: a corrupt/truncated record was ACCEPTED", rejected)
            } else {
                val got = try {
                    hex(codec.decrypt(record))
                } catch (e: Exception) {
                    "<threw: ${e.message}>"
                }
                assertEquals("case $name: plaintext", expect.getString("plaintext"), got)
            }
        }
    }

    @Test
    fun `matches every shared replay-window verdict`() {
        val fx = fixture("replay-window.json")
        requireListed(fx, "replay-window.json")

        // The fixture was generated for a specific window size; a build with a different one
        // would fail cases for a reason unrelated to correctness.
        assertEquals("fixture window size vs this build",
            PacketCodec.REPLAY_WINDOW, fx.getInt("window_size"))

        val cases = fx.getJSONArray("cases")
        assertTrue("fixture file has no cases", cases.length() > 0)

        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            val seqs = c.getJSONArray("seqs")
            val want = c.getJSONArray("verdicts")

            // A FRESH window per case — the codec owns the window, so a fresh codec is a
            // fresh window. The key is irrelevant here: no crypto is exercised.
            val codec = PacketCodec(PacketCipher(ByteArray(32)))
            val got = (0 until seqs.length()).map { codec.acceptCounter(seqs.getLong(it)) }
            val expected = (0 until want.length()).map { want.getBoolean(it) }

            assertEquals("case $name: verdicts for seqs ${seqs}", expected, got)
        }
    }

    /**
     * UDP handshake fragmentation. The reassembler is fed by the NETWORK — out of order, with
     * duplicates, with gaps, and with whatever an attacker sends — so the malformed cases
     * matter as much as the happy ones. The failure this pins against is the classic
     * "works on Wi-Fi, hangs on LTE": IP fragments are dropped on mobile / CGNAT paths, which
     * is the whole reason the handshake is split at the app layer.
     */
    @Test
    fun `fragments, reassembles and classifies every shared vector`() {
        val fx = fixture("udp-frag.json")
        requireListed(fx, "udp-frag.json")

        assertEquals("fixture MAX_CHUNK vs this build", UdpFrag.MAX_CHUNK, fx.getInt("max_chunk"))
        // The receive bound is pinned separately and is LARGER: bounding receive by the send
        // budget would reject every handshake from a pre-#14 peer.
        assertEquals(
            "fixture MAX_CHUNK_ACCEPT vs this build",
            UdpFrag.MAX_CHUNK_ACCEPT,
            fx.getInt("max_chunk_accept"),
        )
        assertEquals("fixture MAX_FRAGS vs this build", UdpFrag.MAX_FRAGS, fx.getInt("max_frags"))

        // ── fragment ────────────────────────────────────────────────────────────
        val frags = fx.getJSONArray("fragment")
        assertTrue("no fragment cases", frags.length() > 0)
        for (i in 0 until frags.length()) {
            val c = frags.getJSONObject(i)
            val name = c.getString("name")
            val msgId = c.getInt("msg_id").toByte()
            val expect = c.getJSONObject("expect")

            if (expect.optBoolean("reject", false)) {
                // The oversize body is megabytes, so the fixture records its SHAPE.
                val len = c.getInt("message_len")
                val big = ByteArray(len) { ((it * 31 + 7) % 256).toByte() }
                val refused = try {
                    UdpFrag.fragment(msgId, big); false
                } catch (_: Exception) {
                    true
                }
                assertTrue("case $name: oversize message was fragmented instead of refused", refused)
            } else {
                val msg = unhex(c.getString("message"))
                val got = UdpFrag.fragment(msgId, msg).map { hex(it) }
                val want = expect.getJSONArray("fragments")
                val expected = (0 until want.length()).map { want.getString(it) }
                assertEquals("case $name: fragments", expected, got)
            }
        }

        // ── reassemble ──────────────────────────────────────────────────────────
        val res = fx.getJSONArray("reassemble")
        assertTrue("no reassemble cases", res.length() > 0)
        for (i in 0 until res.length()) {
            val c = res.getJSONObject(i)
            val name = c.getString("name")
            val expect = c.getJSONObject("expect")
            val feed = c.getJSONArray("feed")

            // A FRESH reassembler per case.
            val re = UdpFrag.Reassembler()
            var completed: ByteArray? = null
            var rejected = false
            for (j in 0 until feed.length()) {
                try {
                    val got = re.push(unhex(feed.getString(j)))
                    if (got != null) { completed = got; break }
                } catch (_: Exception) {
                    rejected = true; break
                }
            }

            when {
                expect.optBoolean("reject", false) ->
                    assertTrue("case $name: a malformed fragment was ACCEPTED", rejected)
                expect.optBoolean("incomplete", false) -> {
                    assertTrue("case $name: an incomplete message was rejected outright", !rejected)
                    assertTrue("case $name: completed a message missing a fragment", completed == null)
                }
                else -> {
                    assertTrue("case $name: never completed (rejected=$rejected)", completed != null)
                    assertEquals("case $name: reassembled message",
                        expect.getString("message"), hex(completed!!))
                }
            }
        }

        // ── classify ────────────────────────────────────────────────────────────
        val cls = fx.getJSONArray("classify")
        assertTrue("no classify cases", cls.length() > 0)
        for (i in 0 until cls.length()) {
            val c = cls.getJSONObject(i)
            val name = c.getString("name")
            val d = unhex(c.getString("datagram"))
            val e = c.getJSONObject("expect")
            assertEquals("case $name: is_fragment", e.getBoolean("is_fragment"), UdpFrag.isFragment(d))
            assertEquals("case $name: is_junk", e.getBoolean("is_junk"), UdpFrag.isJunk(d))
            assertEquals("case $name: is_mtu_probe", e.getBoolean("is_mtu_probe"), UdpFrag.isMtuProbe(d))
            assertEquals("case $name: is_mtu_probe_ack", e.getBoolean("is_mtu_probe_ack"), UdpFrag.isMtuProbeAck(d))
        }
    }

    /**
     * The path-MTU ladder's floor (#12). Rungs are INNER tunnel MTUs, 1280 is an OUTER path
     * limit — so a floor of 1280 asked a 1280-byte path for 1280 + overhead bytes and every
     * rung failed on exactly the narrow paths probing exists for.
     */
    @Test
    fun `mtu ladder floor fits the ipv6 minimum path`() {
        // Both extremes this codebase produces: bare IPv4 UDP, and obfs seal (13) + QUIC short
        // header (9) + UDP (8) + IPv6 (40), each over a 48-byte record overhead.
        for (overhead in intArrayOf(48 + 8 + 20, 48 + 13 + 9 + 8 + 40)) {
            val ladder = MtuLadder.rungs(1400, overhead)
            assertTrue("ladder must not be empty (overhead $overhead)", ladder.isNotEmpty())
            assertTrue(
                "lowest rung ${ladder.last()} + $overhead must fit a 1280-byte path",
                ladder.last() + overhead <= 1280,
            )
            assertEquals("rungs must be strictly descending", ladder.sortedDescending(), ladder)
            assertEquals("rungs must be deduped", ladder.distinct(), ladder)
        }
        // A ceiling already below the floor must still yield something to try, not an empty
        // ladder (which reports "no result" and silently keeps the pushed MTU).
        val tiny = MtuLadder.rungs(700, 48 + 13 + 9 + 8 + 40)
        assertTrue("a low ceiling still produces a rung", tiny.isNotEmpty() && tiny.first() <= 700)
    }

    /**
     * The exact bytes of the in-tunnel MTU report, pinned identically in the Rust, C# and Swift
     * ports. A port that drifts on byte order or the magic makes the server read a nonsense MTU.
     */
    @Test
    fun `ctrl mtu report matches the shared vector`() {
        // 1280 = 0x0500, big-endian.
        assertEquals("c19b01020500", hex(CtrlFrame.mtuReport(1280)))
        assertEquals("clamped, not wrapped", "c19b0102ffff", hex(CtrlFrame.mtuReport(70_000)))
        assertEquals("clamped, not wrapped", "c19b01020000", hex(CtrlFrame.mtuReport(-1)))

        // The discriminator that keeps control frames and IP packets apart, in both directions.
        assertTrue(CtrlFrame.isCtrl(CtrlFrame.mtuReport(1280)))
        assertFalse("IPv4 is not a ctrl frame", CtrlFrame.isCtrl(byteArrayOf(0x45, 0, 0, 0x28)))
        assertFalse("IPv6 is not a ctrl frame", CtrlFrame.isCtrl(byteArrayOf(0x60, 0, 0, 0)))
        assertFalse("heartbeat is not a ctrl frame", CtrlFrame.isCtrl(ByteArray(0)))
    }

    /**
     * Client info (type 2), pinned to the SAME bytes as the Rust, C# and Swift tests so the four
     * implementations cannot drift: `[magic][type=2][len=12][verLen=6]["0.7.13"]["linux"]`.
     */
    @Test
    fun `ctrl client info matches the shared vector`() {
        assertEquals(
            "c19b020c06302e372e31336c696e7578",
            hex(CtrlFrame.clientInfo("0.7.13", "linux")!!),
        )

        // The server REJECTS a bad version or platform outright rather than scrubbing it, so a
        // frame it would refuse must not be built here either. These are the shapes that reach a
        // log line, a terminal table and the panel's DOM.
        val newline = "0.7.13" + 10.toChar() + "X"
        assertNull("a newline forges a log line", CtrlFrame.clientInfo(newline, "linux"))
        assertNull("markup reaches the panel DOM", CtrlFrame.clientInfo("<b>1.0</b>", "linux"))
        assertNull("empty version", CtrlFrame.clientInfo("", "linux"))
        assertNull("over the 32-byte cap", CtrlFrame.clientInfo("9".repeat(33), "linux"))
        assertNull("platform must be lowercase", CtrlFrame.clientInfo("0.7.13", "Linux"))
        assertNull("empty platform", CtrlFrame.clientInfo("0.7.13", ""))
        assertNull("over the 16-byte cap", CtrlFrame.clientInfo("0.7.13", "a".repeat(17)))

        // Valid non-trivial values must still build.
        assertNotNull(CtrlFrame.clientInfo("1.0.0-rc1+build.7", "linux"))
        for (pl in listOf("linux", "windows", "macos", "android", "ios", "freebsd", "other")) {
            assertNotNull("platform $pl must be accepted", CtrlFrame.clientInfo("0.7.13", pl))
        }
        // This build's own tag must be one the server accepts.
        assertNotNull(CtrlFrame.clientInfo("0.7.13", CtrlFrame.PLATFORM))
    }

    /**
     * A pre-#14 peer slices at 1200, which is ABOVE this build's send budget. The reassembler
     * must bound by MAX_CHUNK_ACCEPT, not MAX_CHUNK, or every legacy handshake is rejected as
     * "fragment chunk too large".
     */
    @Test
    fun `legacy 1200-byte chunks still reassemble`() {
        val legacy = 1200
        assertTrue("the send and accept bounds must differ", legacy > UdpFrag.MAX_CHUNK)
        assertTrue("accept bound must cover legacy", legacy <= UdpFrag.MAX_CHUNK_ACCEPT)

        val re = UdpFrag.Reassembler()
        var out: ByteArray? = null
        for (idx in 0 until 2) {
            val d = ByteArray(UdpFrag.HDR_LEN + legacy) { 'L'.code.toByte() }
            UdpFrag.MAGIC.copyInto(d, 0)
            d[3] = UdpFrag.MSG_SERVER_HELLO; d[4] = idx.toByte(); d[5] = 2
            out = re.push(d)
            if (idx == 0) assertNull("must not complete on the first fragment", out)
        }
        assertEquals("legacy message length", legacy * 2, out!!.size)
    }
}
