import XCTest
@testable import Qeli

/// Key derivation and QUIC masking, checked against the SHARED cross-language fixtures
/// `conformance/hkdf.json` and `conformance/quic.json` — both GENERATED by the Rust canon
/// (`qeli/src/gen_conformance_main.rs`).
///
/// WHY HKDF: both ends must derive byte-identical keys or the tunnel does not come up, and a
/// subtler divergence — the two DIRECTIONS swapped — yields a tunnel that authenticates and
/// then decrypts nothing. Three of the four schemes take several 32-byte secrets whose ORDER
/// is wire-format.
///
/// WHY QUIC: the parse half is attacker-facing — anyone who can send this client a datagram
/// controls those bytes, and a crafted varint once crashed the C# and Kotlin parsers into a
/// reconnect loop.
final class CryptoConformanceTests: XCTestCase {

    private func fixture(_ name: String) throws -> [String: Any] {
        var dir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<8 {
            let candidate = dir.appendingPathComponent("conformance/\(name)")
            if FileManager.default.fileExists(atPath: candidate.path) {
                let data = try Data(contentsOf: candidate)
                guard let obj = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                    throw VPNConfigError.invalid("fixtures are not a JSON object")
                }
                return obj
            }
            dir = dir.deletingLastPathComponent()
        }
        XCTFail("conformance/\(name) not found walking up from \(#filePath)")
        throw VPNConfigError.invalid("fixtures not found")
    }

    private func hex(_ d: Data) -> String { d.map { String(format: "%02x", $0) }.joined() }

    private func unhex(_ s: String) throws -> Data {
        var out = Data()
        var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            guard let b = UInt8(s[i..<j], radix: 16) else {
                throw VPNConfigError.invalid("bad hex in fixture: \(s)")
            }
            out.append(b)
            i = j
        }
        return out
    }

    private func requireListed(_ fx: [String: Any], _ label: String) {
        let platforms = fx["platforms"] as? [String] ?? []
        XCTAssertTrue(platforms.contains("swift"), "swift is not listed in `platforms` of \(label)")
    }

    func testDerivesEverySharedKeyVector() throws {
        let fx = try fixture("hkdf.json")
        requireListed(fx, "hkdf.json")

        let cases = fx["cases"] as? [[String: Any]] ?? []
        XCTAssertFalse(cases.isEmpty, "fixture file has no cases")

        for c in cases {
            let name = c["name"] as? String ?? "?"
            let inputs = c["inputs"] as! [String: String]
            func input(_ k: String) throws -> Data { try unhex(inputs[k]!) }

            let keys: (serverToClient: Data, clientToServer: Data)
            switch c["scheme"] as! String {
            case "classic":
                keys = KeyDerivation.classicKeys(sharedSecret: try input("shared_secret"))
            case "hybrid":
                keys = KeyDerivation.hybridKeys(
                    x25519Shared: try input("x25519_shared"),
                    mlkemShared: try input("mlkem_shared"))
            case "bound":
                keys = KeyDerivation.boundClassicKeys(
                    ephemeralShared: try input("ee"),
                    staticShared: try input("es"))
            case "hybrid-bound":
                keys = KeyDerivation.boundHybridKeys(
                    x25519Shared: try input("x25519_shared"),
                    mlkemShared: try input("mlkem_shared"),
                    staticShared: try input("es"))
            case let other:
                XCTFail("case \(name): unknown scheme `\(other)`")
                continue
            }

            let expect = c["expect"] as! [String: String]
            XCTAssertEqual(hex(keys.serverToClient), expect["server_to_client"]!,
                           "case \(name): server_to_client")
            XCTAssertEqual(hex(keys.clientToServer), expect["client_to_server"]!,
                           "case \(name): client_to_server")
        }
    }

    func testMasksAndParsesEverySharedQUICVector() throws {
        let fx = try fixture("quic.json")
        requireListed(fx, "quic.json")

        let wraps = fx["wrap"] as? [[String: Any]] ?? []
        XCTAssertFalse(wraps.isEmpty, "fixture has no wrap cases")
        for w in wraps {
            let name = w["name"] as? String ?? "?"
            let payload = try unhex(w["payload"] as! String)
            let cid = try unhex(w["connection_id"] as! String)
            let pn = (w["packet_number"] as! NSNumber).uint32Value

            let packet = try QUICMask.wrapShort(payload, connectionID: cid, packetNumber: pn)
            let expect = w["expect"] as! [String: String]
            XCTAssertEqual(hex(packet), expect["packet"]!, "case \(name): wrapped packet")

            let back = QUICMask.unwrap(packet)
            XCTAssertNotNil(back, "case \(name): own output failed to parse")
            XCTAssertEqual(hex(back ?? Data()), hex(payload), "case \(name): payload round-trip")
        }

        let parses = fx["parse"] as? [[String: Any]] ?? []
        XCTAssertFalse(parses.isEmpty, "fixture has no parse cases")
        for p in parses {
            let name = p["name"] as? String ?? "?"
            let packet = try unhex(p["packet"] as! String)
            let expect = p["expect"] as! [String: Any]

            // A crafted packet must be rejected CLEANLY — nil, not a trap and not an
            // allocation sized from an attacker-supplied length.
            let got = QUICMask.unwrap(packet)
            if (expect["reject"] as? Bool) == true {
                XCTAssertNil(got, "case \(name): a crafted packet was ACCEPTED")
            } else {
                XCTAssertNotNil(got, "case \(name): a valid packet was rejected")
                XCTAssertEqual(hex(got ?? Data()), expect["payload"] as! String, "case \(name): payload")
            }
        }
    }
}
